### ISSUE TITLE
Quasar Layout <router-view> bug with Typescript

### ISSUE THREAD

**Issue by l1qu1d** [quasarframework/app-extension-typescript#37] opened 2019-09-18 00:25 UTC
**Describe the bug**
When adding this extension to a **brand new** Quasar project and then running "quasar dev" I get a `<router-view>` error in the console window in Google Chrome.

**To Reproduce**
1. Install quasar via `quasar create`, with default options
2. Install this extension via `quasar ext add @quasar/typescript`, with default options
3. Run the dev environment via `quasar dev`
4. In the web browser of your choice, open the console
You should notice an error that says:
```
[Vue warn]: Unknown custom element: <router-view> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
found in
---> <MyLayout> at src/layouts/MyLayout.vue
       <App> at src/App.vue
         <Root>
```

**Platform (please complete the following information):**
OS: Windows 10
Node: 10.16.3
NPM: 6.9.0
Yarn: N/A, although I did also try with the latest Yarn and fresh install (total new project) with the same result
Browsers: Google Chrome

**Additional context**
Even after installing the extension, if you revert it back to the original script section, it works with no error. I've also tried it two different typescript implementations and still had the same problem.

TS Implementations:
```
export default class MyLayout extends Vue {}
```
and
```
export default Vue.extend({})
```

Installed original script:
```
<script>
import { openURL } from "quasar";

export default {
  name: "MyLayout",
  data() {
    return {
      leftDrawerOpen: false
    };
  },
  methods: {
    openURL
  }
};
</script>
```

**Comment by luozhihua** [comment] 2019-09-18 12:49
Same issues.

**Comment by Arsync** [comment] 2019-09-19 07:42
As a quick fix, it conflicts with `framework.all: 'auto'` option in 'quasar.conf.js'. Try to set `framework.all: true` to test.

**Comment by webnoob** [comment] 2019-09-19 08:04
@rstoenescu Mentioning you here so you know it's an issue.

@Arsync Ran a test for me:

Created with:
- framework.all: true,
- fork-ts-checker-webpack-plugin option
- rename .js to .ts - yes
- VSCode for project - yes
- Generate prettier - yes
So, when starting it with quasar dev -m ssr, it works fine. Index.vue shown.

Changing framework.all: 'auto', launching again and got router view error.

It seems it's directly related to the new option. Will try and investigate later today.

**Comment by Cmacu** [comment] 2019-10-04 05:49
Encountered the same issue here. I get the router-view error when the auto tree shaking feature is enabled and everything works fine when all components are imported.

**Comment by xparagon** [comment] 2019-11-15 11:34
Any ETA for this issue?

**Comment by Juliaandavid** [comment] 2019-11-18 02:22
Any update of this bug?

Same here with:
Ubuntu 19.10
Node: 8.16.2
Yarn: 1.19.1
Browsers: Google Chrome

**Comment by xparagon** [comment] 2019-11-20 08:38
Listing all components under framework: solved it for us ;-)

**Comment by l1qu1d** [comment] 2019-11-20 21:40
Doing 'all' defeats the purpose of having it automatically add the required Quasar components and directives. I'm about to make my project live for Jan 2020 and if this isn't fixed before then, I'm going to have to go through and see where it errors out to 'manually' add them to the framework. If I don't, I won't have a minimal bundle size.

**Comment by stphdenis** [comment] 2019-12-04 09:41
Default paths don't work so we have to import `MyLayout` staticaly :
```ts
import { RouteConfig } from 'vue-router'
import MyLayout from 'layouts/MyLayout.vue'

const routes: RouteConfig[] = [
  {
    path: '/',
    component: MyLayout,
    children: [
      { path: '', component: () => import('pages/Index.vue') }
    ]
  }
]
```

**Comment by l1qu1d** [comment] 2019-12-11 08:36
While @stphdenis solution will compile and be OK on the home page. It doesn't work for me navigating to other pages in my website and the same errors occur as the original problem. With this solution it will appear fine (which is better than showing up blank), but will make the `router-link`s un-clickable that are wrapped within MyLayout.

Just in case this is an edge case, this is my setup:
-  SSR (server side rendering) with PWA (progressive web app) --I also tried this is SPA (single page application) mode
- `vueRouterMode` is set to `"history"` in quasar.conf.js
- `router-link` and `q-item` for navigation

**Comment by webnoob** [comment] 2019-12-12 17:13
I've tracked down the cause of this issue. 

We're working on a fix.

**Comment by webnoob** [comment] 2019-12-13 19:03
Razvan has pushed a fix pending release. I've tested it and `all: 'auto'` is now working.

**Comment by rstoenescu** [comment] 2019-12-14 12:27
Using "@quasar/app" v1.4.1 should have this fixed.

**Closed as completed by rstoenescu** 2019-12-14 12:27 UTC
