### ISSUE TITLE
Error when using Component Decorator

### ISSUE THREAD

**Issue by caboe** [quasarframework/app-extension-typescript#17] opened 2019-04-11 10:51 UTC
When using the "vue-property-decorator" the following error occurs:
Parsing error: Using the export keyword between a decorator and a class is not allowed. Please use `export @dec class` instead.
Can be fixed by adding this to the .eslintrc.js parserOptions:
`{
  parserOptions: {
    ecmaFeatures: {
      legacyDecorators: true
    }
  }
}`

**Comment by outofmemoryagain** [comment] 2019-07-22 16:56
Now that #22 is merged, this one should be added as part of the base template for eslint.

**Comment by frck006** [comment] 2019-12-21 17:10
The problem is already here. Not resolved.

**Comment by IlCallo** [comment] 2020-04-14 08:48
Can you check if this still happens with latest starter kit update, which officially adds TS support when creating a new project?

**Closed as completed** 2020-10-05 11:32 UTC
